-- Tabela de Usuários
create table public.users (
  id bigint generated by default as identity primary key,
  email text unique not null,
  auth_user_id uuid unique,
  password_hash text,
  role text not null default 'user',
  name text,
  bio text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Tabela de Posts
create table public.posts (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  title text not null,
  excerpt text not null,
  content text not null,
  category text not null default 'Geral',
  tags text not null default '[]',
  source_url text,
  author_name text,
  author_email text,
  author_id bigint references public.users(id) on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Tabela de Tópicos (Forum)
create table public.topics (
  id bigint generated by default as identity primary key,
  category text not null default 'Geral',
  title text not null,
  body text not null,
  author_name text,
  author_email text,
  status text not null default 'pending',
  author_id bigint references public.users(id) on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Tabela de Comentários
create table public.comments (
  id bigint generated by default as identity primary key,
  parent_type text not null check (parent_type in ('post', 'topic')),
  parent_id bigint not null,
  body text not null,
  author_name text,
  author_email text,
  author_id bigint references public.users(id) on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Índices
create index if not exists idx_posts_created on public.posts(created_at);
create index if not exists idx_topics_created on public.topics(created_at);
create index if not exists idx_comments_parent on public.comments(parent_type, parent_id);

-- Tabela de Produtos (Loja)
create table public.products (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  name text not null,
  summary text not null,
  details text,
  price_cents integer not null default 0,
  currency text not null default 'BRL',
  image_url text,
  active boolean not null default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists idx_products_active on public.products(active);

-- Migracoes para base existente:
-- alter table public.users add column if not exists auth_user_id uuid;
-- alter table public.users alter column password_hash drop not null;
-- create unique index if not exists users_auth_user_id_key on public.users(auth_user_id);
-- alter table public.posts add column if not exists author_name text;
-- alter table public.posts add column if not exists author_email text;
-- alter table public.topics add column if not exists author_name text;
-- alter table public.topics add column if not exists author_email text;
-- alter table public.topics add column if not exists status text not null default 'pending';
-- alter table public.comments add column if not exists author_name text;
-- alter table public.comments add column if not exists author_email text;
-- update public.topics set status = 'approved' where status is null;
